Institutos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('Ingresar/', views.login, name='ingresar'),
    path('on_login', views.on_login, name='on_login'),
    
    path('RecuperarPassword/', views.password_reset, name='password_reset'),
    path('Recuperar/<hash_id>/', views.password_confirm, name='password_confirm'),
    #path(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    #path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    #path(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    path('Registro', views.registro, name='registro'),
    path('Perfil', views.perfil, name='perfil'),
    path('Perfil_edit', views.perfil_edit, name='perfil_edit'),
    path('Buscar', views.buscar, name='buscar'),
    path('BuscarProfe', views.buscarProfe, name='buscarProfe'),
    path('Instituto/<int:instituto_id>/', views.institutoByID, name='instituto'),
    path('Instituto/<slug:nombre>/', views.instituto, name='instituto_nombre'),
    #path('Instituto/<int:instituto_id>/Nuevo-Mensaje', views.nuevo_mensaje, name='nuevo_mensaje'),
    path('Contacto/', views.contacto, name='contacto'),
    path('Contacto/<int:instituto_id>/', views.contacto, name='contacto'),
    path('Sobre-Nosotros', views.sobre_nosotros, name='nosotros'),
    #path('PruebaCorreo', views.prueba_correo, name='prueba_correo'),
    path('admin/mensajes/', views.mensajes, name='mensajes'),
    path('admin/leidos/', views.leidos, name='leidos'),
    path('admin/Pendientes/', views.pendientes, name='pendientes'),
    path('admin/Activos/', views.activos, name='activos'),
    path('admin/Inactivos/', views.inactivos, name='inactivos'),
    path('admin/marcarLeido/<int:mensaje_id>/', views.marcar_leido, name='marcar_leido'),
    #path('admin/mandar_link/<int:mensaje_id>/', views.mandar_link, name='mandar_link'),
    path('admin/habilitarInstituto/<int:id>/', views.habilitarInstituto, name='habilitar_instituto'),
    path('admin/deshabilitarInstituto/<int:id>/', views.deshabilitarInstituto, name='deshabilitar_instituto'),
    path('admin/cargarParadas', views.cargarParadas, name='cargar_paradas'),
    path('Activar/<hash_id>/', views.activar, name='activar'),
    path('admin/paradasCoords/', views.paradasCoords, name='paradasCoords'),
    path('admin/generarSlugs/', views.generarSlugs, name='generarSlugs'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TuProfe/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import include, path

urlpatterns = [
    path('', include('Institutos.urls')),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

Institutos/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import hashlib
import math

class UsuarioLegado(models.Model):
    username = models.CharField(max_length=30)
    email = models.CharField(max_length=50, null=True)
    password = models.CharField(max_length=32, null=True)
    activo = models.BooleanField(default=False)
    migrado = models.BooleanField(default=False)

    def __str__(self):
        return "%s - %s" % (self.username, self.email)

    def check_password(self, password):
        m = hashlib.md5()
        m.update(password.encode('utf-8'))
        print(self.password)
        print(m.hexdigest())
        return self.password==m.hexdigest()

    def is_active(self):
        return self.activo

class Calle(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
        
class Omnibus(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Parada(models.Model):
    latitud = models.FloatField(default=0)
    longitud = models.FloatField(default=0)
    calle = models.ForeignKey(Calle, on_delete=models.PROTECT, related_name='calle')
    esquina = models.ForeignKey(Calle, on_delete=models.PROTECT, related_name='esquina')
    lineas = models.ManyToManyField(Omnibus)

    def __str__(self):
        return "%s - %s - %s (%s, %s)" % (self.id, self.calle, self.esquina, self.latitud, self.longitud)
        
class Facilidad(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return "%s" % (self.nombre)
    
class FormaPago(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return "%s" % (self.nombre)
    
class Comodidad(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return "%s" % (self.nombre)
    
class RedSocial(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return "%s" % (self.nombre)
    
class Motivo(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return "%s" % (self.nombre)

class Barrio(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return "%s" % (self.nombre)
    
class Centro(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return "%s" % (self.nombre)

class Materia(models.Model):
    nombre = models.CharField(max_length=50)
    centro = models.ForeignKey(Centro, on_delete=models.PROTECT)

    def __str__(self):
        return "%s - %s" % (self.centro, self.nombre)

class Instituto(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.PROTECT)
    estado = models.IntegerField(default=0, null=True)
    hash_id = models.CharField(max_length=32, null=True)
    referencia = models.IntegerField(default=0, null=True)
    logo =  models.ImageField(upload_to='profile_pics/', default = 'profile_pics/blank-profile.jpg')
    nombre = models.CharField(max_length=50, default='')
    slug = models.CharField(max_length=50, default='')
    subtitulo = models.CharField(max_length=500, default='')
    descripcion = models.CharField(max_length=2000, default='')
    descripcion_corta = models.CharField(max_length=500, default='')
    telefono = models.CharField(max_length=50, null=True)
    celular = models.CharField(max_length=50, null=True)
    direccion = models.CharField(max_length=300, default='', null=True)
    ciudad = models.CharField(max_length=50, default='Montevideo')
    departamento = models.CharField(max_length=50, default='Montevideo')
    pais = models.CharField(max_length=50, default='Uruguay')
    latitud = models.FloatField(default=0)
    longitud = models.FloatField(default=0)
    creado = models.DateTimeField(default=datetime.now, null=True)
    modificado = models.DateTimeField(default=datetime.now, null=True)
    posicionamiento = models.IntegerField(default=0)
    esDestacado = models.NullBooleanField(default=False)
    facilidades = models.ManyToManyField(Facilidad, blank=True)
    formasPago = models.ManyToManyField(FormaPago, blank=True)
    comodidades = models.ManyToManyField(Comodidad, blank=True)
    barrios = models.ManyToManyField(Barrio, blank=True)
    centros = models.ManyToManyField(Centro, blank=True)
    materias = models.ManyToManyField(Materia, blank=True)
    omnibuses = models.ManyToManyField(Omnibus, blank=True)
    
    ultima_distancia = 0

    def distancia(self, lat, lng):
        radius = 6371 # km
        dlat = math.radians(lat-self.latitud)
        dlon = math.radians(lng-self.longitud)
        a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(self.latitud)) \
            * math.cos(math.radians(lat)) * math.sin(dlon/2) * math.sin(dlon/2)
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
        d = radius * c
        self.ultima_distancia = d
        return d

    def updateRelation(self, attribute, ids):
        elems = attribute.all()
        for e in elems:
            attribute.remove(e)
        for i in ids.all():
            attribute.add(i)

    def update_hash(self):
        m = hashlib.md5()
        m.update(self.nombre.encode('utf-8'))
        self.hash_id = m.hexdigest()

    def update_hash_pass(self):
        m = hashlib.md5()
        if self.hash_id == None:
            m.update(self.nombre.encode('utf-8'))
            self.hash_id = m.hexdigest()
        m.update((self.hash_id + self.nombre).encode('utf-8'))
        self.hash_id = m.hexdigest()

    def __str__(self):
        return "%s - %s" % (self.id, self.nombre)

class Profesor(models.Model):
    nombre = models.CharField(max_length=500)
    instituto = models.ForeignKey(Instituto, on_delete=models.PROTECT)

    def __str__(self):
        return "%s - %s" % (self.instituto, self.nombre)

class Enlace(models.Model):
    instituto = models.ForeignKey(Instituto, on_delete=models.PROTECT)
    redSocial = models.ForeignKey(RedSocial, on_delete=models.PROTECT)
    link = models.CharField(max_length=200)
    
    def __str__(self):
        return "%s - %s" % (self.instituto, self.redSocial)

class Mensaje(models.Model):
    fecha = models.DateTimeField()
    nombre = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    asunto = models.CharField(max_length=200, null=True)
    mensaje = models.CharField(max_length=4000)
    motivo = models.ForeignKey(Motivo, on_delete=models.PROTECT, blank=True, null=True)
    instituto = models.ForeignKey(Instituto, on_delete=models.PROTECT, blank=True, null=True)
    centro = models.ForeignKey(Centro, on_delete=models.PROTECT, blank=True, null=True)
    leido = models.BooleanField(default=False)
    linkEnviado = models.BooleanField(default=False)
    emailVerificado = models.BooleanField(default=False)

    def __str__(self):
        return "%s - %s" % (self.fecha, self.nombre)

Institutos/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Instituto

from django.db import models

class Image(models.Model):
    logo = models.ImageField(upload_to='profile_pics/')

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('logo', )

class SignUpForm(forms.Form):
    name = forms.CharField(max_length=30, label='Nombre')
    cellphone = forms.CharField(max_length=30, label='Telefono')
    username = forms.CharField(max_length=254, label='Correo')
    password1 = forms.CharField(widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirmar Password')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'name', 'cellphone', )

class PerfilForm(forms.ModelForm):
    email = forms.CharField(max_length=254, label='Correo')

    class Meta:
        model = Instituto
        fields = ('nombre', 'descripcion', 'email', 'logo', \
            'telefono', 'direccion', 'latitud', 'longitud', 'centros', \
            'materias', 'facilidades', 'formasPago', 'comodidades', )

Institutos/templates/Institutos/Contacto.html
{% extends "Institutos/base.html" %}

{% block titleH1 %}
  <h1 class="titleH1">
	Contactáte
  </h1>
{% endblock %}


{% block content %}

	<div class="breadcrum">
		<div class="max">
			<span><a href="/">Inicio</a></span>
			<span class="separa">&nbsp;>>&nbsp;</span>
			<span>Contactáte</span>				
		</div>
	</div>
	{% if errores %}
		{% include "Institutos/Mensaje_Show.html" with mensaje=errores instituto_id=instituto_id %}
	{% endif %}
	
	{% if instituto_id != 0 and errores != "El mensaje ha sido enviado correctamente." or instituto_id == 0 %}
		<section class="interna">
			<article class="message">
				<img src="/static/Institutos/theme/img/info.gif">
				<form name="contacto" action="{% url 'contacto' instituto_id %}" method="post">
					{% csrf_token %}
					<div class="formularioContacto">
						<p>Contactáte</p>

						<div id='err_nombre' class="error" hidden>El ingreso del nombre es obligatorio.</div>
						<input type="text" name="nombre" class="dir" placeholder="Nombre y Apellido" value="{{ mensaje.nombre }}">
						<input type="text" name="telefono" class="dir" placeholder="Teléfono" value="{{ mensaje.telefono }}">

						<div id='err_email' class="error" hidden>El ingreso del correo electrónico es obligatorio.</div>
						<div id='err_email2' class="error" hidden>El correo electrónico ingresado no es válido.</div>
						<input type="email" name="email" class="dir" placeholder="Correo electrónico" value="{{ mensaje.email }}">
						<input type="text" name="asunto" class="dir" placeholder="Asunto" value="{{ mensaje.asunto }}">

						<div id='err_mensaje' class="error" hidden>El ingreso del mensaje es obligatorio.</div>
						<textarea name="mensaje" rows="4" cols="50" placeholder="Ingrese su mensaje...">{{ mensaje.mensaje }}</textarea>
						<div type="submit" class="search" onclick="javascript:validateContactoForm();">Enviar</div>
					</div>
				</form>
			</article>      
		</section>
	{% endif %}

{% endblock %}

Institutos/templates/Institutos/Instituto.html
{% extends "Institutos/base.html" %}

{% load Institutos_extras %}

{% load staticfiles %}


{% block toHeadTop %} 
    <div class="fichaPerfilProfe">
        <img src="{{ MEDIA_URL }}profile_pics/{{ instituto.logo }}" style="border-radius: 5px;">
        <div class="rightInfo">
            <h3>{{ instituto.nombre }}</h3>
            <span><img src="/static/Institutos/theme/img/pin_address.png" alt="Dirección" style="width: 19px;">{{ instituto.direccion }}</span>
            <div class="bottomInfo">
				<span class="km"><b>{{ instituto.ultima_distancia }}</b> Km distancia</span>
                <div id="telefono" class="telefono" style="display: none; text-decoration: none; cursor: auto;">Teléfono: {{ instituto.telefono }}</div><a class="telefono" id="link" href="#" onclick="clickTelefono()">Ver teléfono</a> 
            </div>
        </div>
    </div>

{% endblock %}



{% block content %}
	<script src="{% static "Institutos/telefono.js" %}"></script>
	<script>
		jQuery(document).ready(function() {
			jQuery(jQuery("header.interna")[0]).addClass("perfilProfe");
		});
	</script>

	<div class="breadcrum">
		<div class="max">
			<span><a href="/">Inicio</a></span>
			<span class="separa">&nbsp;>>&nbsp;</span>
			<span>Profe</span>
			<span class="separa">&nbsp;>>&nbsp;</span>
			<span>{{ instituto.nombre }}</span>
		</div>
	</div>
	<section class="interna">
		<div id="formularioRespEnvioProfe"></div>
		<div class="max paddTop">				
			<div class="leftBig">
				<div class="perfilMenu">
					<a href="#anclaDescripcion"><span>Descripción</span></a>
					<a href="#anclaUbicacion"><span>Ubicación</span></a>
					<a href="#anclaMaterias"><span>Materias</span></a>
					<a href="#anclaProfesores"><span>Profesores</span></a>
					<a href="#anclaMedioPago"><span>Medios de pago</span></a>
					<a href="#anclaComodidades"><span>Comodidades</span></a>
					<a href="#anclaFacilidades"><span>Facilidades</span></a>
				</div>
				<div class="perfilBox">
					<a name="anclaDescripcion" id="anclaDescripcion"></a>
					<span>Descripción</span>
					<p>
						{{ instituto.descripcion }}
					</p>
				</div>
				<div class="perfilBox">
					<a name="anclaUbicacion" id="anclaUbicacion"></a>
					<span>Ubicación</span>
					<p>
												
						<input id="lat" value="{{ instituto.latitud }}" type="number" hidden>
						<input id="lng" value="{{ instituto.longitud }}" type="number" hidden>


						<div id="map" style="height: 250px; width: 100%;"></div>

					</p>
					<div class="perfilBox">
						<span class="subTitle">Transporte</span>
						<p class="buses">
							{% for f in instituto.omnibuses.all %}
								<span>{{ f.nombre }}</span>
							{% endfor %}
						</p>
					</div>
				</div>
				<div class="perfilBox">
					<a name="anclaMaterias" id="anclaMaterias"></a>
					<span>Materias</span>
					{% for c in instituto.centros.all %}
						<p>
							<span class="centroEstudio">{{ c.nombre }}</span>
							
							{% for m in instituto.materias.all|with_centro:c %}
								<div class="boxBox">{{ m.nombre }}</div>
							{% endfor %}
						</p>
					{% endfor %}
				</div>
				<div class="perfilBox">
					<a name="anclaProfesores" id="anclaProfesores"></a>
					<span>Profesores</span>
					<p>
						{% for p in instituto.profesor_set.all %}
							<div class="boxBox">{{ p.nombre }}</div>
						{% endfor %}
					</p>
				</div>
				<div class="perfilBox">
					<a name="anclaMedioPago" id="anclaMedioPago"></a>
					<span>Medios de pago</span>
					<p>
						{% for f in instituto.formasPago.all %}
							<div class="boxBox">{{ f.nombre }}</div>
						{% endfor %}
					</p>
				</div>
				<div class="perfilBox">
					<a name="anclaComodidades" id="anclaComodidades"></a>
					<span>Comodidades</span>
					<p>
						{% for f in instituto.comodidades.all %}
							<div class="boxBox">{{ f.nombre }}</div>
						{% endfor %}
					</p>
				</div>
				<div class="perfilBox">
					<a name="anclaFacilidades" id="anclaFacilidades"></a>
					<span>Facilidades</span>
					<p>
						{% for f in instituto.facilidades.all %}
							<div class="boxBox">{{ f.nombre }}</div>
						{% endfor %}
					</p>
				</div>
			</div>
			<div class="rightMin">
				<div class="contactoForm profePage">
					<form name="contacto" action="{% url 'contacto' instituto.id %}" method="post">
						{% csrf_token %}
						<h2>Consultas al profesor</h2>
						<p>Completá este formulario y el profesor se pondrá en contacto contigo.</p>
						
						<div id='err_nombre' class="error" hidden>El ingreso del nombre es obligatorio.</div>
						<input type="text" name="nombre" class="dir" placeholder="Nombre y Apellido">
						<input type="text" name="telefono" class="dir" placeholder="Telefono (opcional)">
						
						<div id='err_email' class="error" hidden>El ingreso del correo electrónico es obligatorio.</div>
						<div id='err_email2' class="error" hidden>El correo electrónico ingresado no es válido.</div>
						<input type="email" name="email" class="dir" placeholder="Correo electrónico">
						<input type="text" name="asunto" class="dir" placeholder="Asunto">
						
						<div id='err_mensaje' class="error" hidden>El ingreso del mensaje es obligatorio.</div>
						<textarea name="mensaje" rows="4" cols="50" placeholder="Ingrese su mensaje..."></textarea>
						<div type="submit" class="dir" onclick="javascript:validateContactoForm(true);">Enviar consulta</div>
					</form>
				</div>
			</div>
		</div>
	</section>



{% endblock %}

        

{% block initMapScript %}
	<script>
		function initMap() {
			var position = { lat: parseFloat(document.getElementById('lat').value), lng: parseFloat(document.getElementById('lng').value) };

			var map = new google.maps.Map(document.getElementById('map'), {
				zoom: 15,
				center: position
			});
			var marker = new google.maps.Marker({
				position: position,
				map: map
			});
		}
	</script>
{% endblock %}

Institutos/templates/Institutos/Instituto_Mini.html
<li>
    <a href="{% url 'instituto_nombre' instituto.slug %}">{{ instituto.nombre }}</a>
    <div>Logo: {{ instituto.logo }}</div>
    <div>Dirección: {{ instituto.direccion }}</div>
    <div>Materias Destacadas: {{ instituto.materias.all|join:", " }}</div>
    <div>Distancia: {{ instituto.ultima_distancia|floatformat:1 }} Km</div>
    <div>Horario: 9:00 a 20:00</div>
</li>

Institutos/templates/Institutos/Instituto_Mini_debug.html
<li>
    <a href="{% url 'instituto_nombre' instituto.slug %}">{{ instituto.nombre }}</a>
    <div>Logo: {{ instituto.logo }}</div>
    <div>Dirección: {{ instituto.direccion }}</div>
    <div>Posicionamiento: {{ instituto.posicionamiento }}</div>
    <div>Distancia: {{ instituto.ultima_distancia|floatformat:1 }} Km</div>
    <div>Horario: 9:00 a 20:00</div>
</li>

Institutos/templates/Institutos/Instituto_Simple.html
<li>
    <a href="{% url 'instituto_nombre' instituto.slug %}">{{ instituto.nombre }}</a>
    <div>Logo: {{ instituto.logo }}</div>
    <div>Dirección: {{ instituto.direccion }}</div>
    <div>Materias Destacadas: {{ instituto.materias.all|join:", " }}</div>
</li>

Institutos/templates/Institutos/Mensaje.html
{% extends "Institutos/base.html" %}

{% block titleH1 %}
  <h1 class="titleH1">
	  {{ titulo }}
  </h1>
{% endblock %}

{% block content %}
	<div class="breadcrum">
		<div class="max">
			<span><a href="/">Inicio</a></span>
			<span class="separa">&nbsp;>>&nbsp;</span>
			<span>{{ titulo }}</span>				
		</div>
	</div>

	{% include "Institutos/Mensaje_Show.html" with mensaje=mensaje %}
{% endblock %}

Institutos/templates/Institutos/Perfil.html
{% extends "Institutos/base.html" %}

{% load Institutos_extras %}

{% load staticfiles %}


{% block titleH1 %} 
    <h1 class="titleH1">{{ instituto.nombre }}</h1>

{% endblock %}





{% block content %}


    <div class="breadcrum">
        <div class="max">
            <span><a href="/">Inicio</a></span>
            <span class="separa">&nbsp;>>&nbsp;</span>
            <span>{{ instituto.nombre }}</span>
        </div>
    </div>


    <div class="max">
        <div class="titleRes ajusteMargin"></div>
    </div>
    <section class="interna">
        <div class="max">
            <div class="reeadInfo">
                <div class="title">
                    <h2>Información b&aacute;sica</h2>
                    <a href="{% url 'perfil_edit' %}">Editar</a>
                </div>
                <div class="reeadBox" id="infoBasca">
                    <img src="{{ MEDIA_URL }}profile_pics/{{ instituto.logo }}" style="max-height: 115px;">
                    <div class="reeadBoxInfo">
                        <p hidden>{{ instituto.id }}</p>
                        <span>Nombre Instituci&oacute;n</span>
                        <p>{{ instituto.nombre }}</p>
                        <span>Teléfono</span>
                        <p>{{ instituto.telefono }}</p>
                        <span>Email de contacto</span>
                        <p>{{ instituto.usuario.email }}</p>
                        <span>Descripc&oacute;n</span>
                        <p>{{ instituto.descripcion }}</p>
                        
							
                    </div>
                </div>
            </div>
            <div class="reeadInfo">
                <div class="title">
                    <h2>Ubicaci&oacute;n</h2>
                    <a href="{% url 'perfil_edit' %}">Editar</a>
                </div>
                <div class="reeadBox" id="ubicacion">
                    <div class="readLeftUbicacion">
                
                        <input id="lat" value="{{ instituto.latitud }}" type="number" hidden>
                        <input id="lng" value="{{ instituto.longitud }}" type="number" hidden>

                        <div id="map" style="height: 150px; width: 100%;"></div>

                        Ubicación en el mapa
                    </div>
                    <div class="readRightUbicacion">
                        <span>Direcci&oacute;n</span>
                        <p>{{ instituto.direccion }}</p>
                        <span>Transporte</span>
                        <p class="buses">
                            {% for f in instituto.omnibuses.all %}
                                <span>{{ f.nombre }}</span>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="max">
            <div class="reeadInfo">
                <div class="title">
                    <h2>Medios de pago</h2>
                    <a href="{% url 'perfil_edit' %}">Editar</a>
                </div>
                <div class="reeadBox" id="mediosPago">
                    {% if instituto.formasPago.all %}
                        <p>
                            {% for f in instituto.formasPago.all %}
                                <div class="boxBox">{{ f.nombre }}</div>
                            {% endfor %}
                        </p>
                    {% else %}
                        <div class="reeadBoxInfo">
                            <span>Sin datos ingreados a&uacute;n.</span>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="reeadInfo">
                <div class="title">
                    <h2>Profesores</h2>
                    <a href="{% url 'perfil_edit' %}">Editar</a>
                </div>
                <div class="reeadBox" id="profesores">
                    {% if instituto.profesor_set.all %}
                        <p>
                            {% for p in instituto.profesor_set.all %}
                                <div class="boxBox">{{ p.nombre }}</div>
                            {% endfor %}
                        </p>
                    {% else %}
                        <div class="reeadBoxInfo">
                            <span>Sin datos ingreados a&uacute;n.</span>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="max">
            <div class="reeadInfo">
                <div class="title">
                    <h2>Facilidades</h2>
                    <a href="{% url 'perfil_edit' %}">Editar</a>
                </div>
                <div class="reeadBox" id="facilidades">
                    {% if instituto.facilidades.all %}
                        <p>
                            {% for f in instituto.facilidades.all %}
								<div class="boxBox">{{ f.nombre }}</div>
                            {% endfor %}
                        </p>
                    {% else %}
                        <div class="reeadBoxInfo">
                            <span>Sin datos ingreados a&uacute;n.</span>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="reeadInfo">
                <div class="title">
                    <h2>Comodidades</h2>
                    <a href="{% url 'perfil_edit' %}">Editar</a>
                </div>
                <div class="reeadBox" id="comodidades">
                    {% if instituto.comodidades.all %}
                        <p>
                            {% for f in instituto.comodidades.all %}
								<div class="boxBox">{{ f.nombre }}</div>
                            {% endfor %}
                        </p>
                    {% else %}
                        <div class="reeadBoxInfo">
                            <span>Sin datos ingreados a&uacute;n.</span>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="max">
            <div class="reeadInfoFull">
                <div class="title">
                    <h2>Materias</h2>
                    <a href="{% url 'perfil_edit' %}">Editar</a>
                </div>
                <div class="reeadBox" id="materias">
                    {% for c in instituto.centros.all %}
                        <p>
							<span class="centroEstudio">{{ c.nombre }}</span>
                            
                            {% for m in instituto.materias.all|with_centro:c %}
							    <div class="boxBox">{{ m.nombre }}</div>
                            {% endfor %}
						</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

        

{% block initMapScript %}
    <script>
        function initMap() {
            var position = { lat: parseFloat(document.getElementById('lat').value), lng: parseFloat(document.getElementById('lng').value) };

            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 15,
                center: position
            });
            var marker = new google.maps.Marker({
                position: position,
                map: map
            });
        }
    </script>
{% endblock %}